/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador.view;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetointegrador.Controller.FornecedorController;

/**
 *
 * @author carlo
 */
public class TelaCadForn extends javax.swing.JFrame {
    String modoTela = "Criar";

    /**
     * Creates new form TelaCadForn
     */
    public TelaCadForn() {
        initComponents();
        
        DesabilitarFormulario();
        
        //Consulta no banco de dados os clientes já cadastrados
        CarregarTabela();
        
        setLocationRelativeTo(null);
    }
    public void HabilitarFormulario(){
    
        
        this.jtNome.setEnabled(true);
        this.jfCNPJ.setEnabled(true);
        this.jtBairro.setEnabled(true);
        this.jfCEP.setEnabled(true);
        this.jtCidade.setEnabled(true);
        this.jtEndereco.setEnabled(true);
        this.jfTelefone.setEnabled(true);
        this.jtUF.setEnabled(true);
        this.bntSalvar.setEnabled(true);
        this.bntCancelar.setEnabled(true);
        
    }
    public void DesabilitarFormulario(){
    
        
        this.jtNome.setEnabled(false);
        this.jfCNPJ.setEnabled(false);
        this.jtBairro.setEnabled(false);
        this.jfCEP.setEnabled(false);
        this.jtCidade.setEnabled(false);
        this.jtEndereco.setEnabled(false);
        this.jfTelefone.setEnabled(false);
        this.jtUF.setEnabled(false);
        this.bntSalvar.setEnabled(false);
        this.bntCancelar.setEnabled(false);
    }
    public void LimparFormulario(){
        
        this.jblIDF.setText("");
        this.jtNome.setText("");
        this.jfCNPJ.setText("");
        this.jtBairro.setText("");
        this.jfCEP.setText("");
        this.jtCidade.setText("");
        this.jtEndereco.setText("");
        this.jfTelefone.setText("");
        this.jtUF.setText("");
        this.jblCampNome.setText("");
    }
    
    
     public void CarregarTabela(){
        
        //Peço ao controller resgatar os clientes do banco de dados
        ArrayList<String[]> linhasFornecedor = FornecedorController.consultarFornecedor();
        
        //Opção 1 - Crio manualmente um modelo para a tabela e defino as colunas
        DefaultTableModel tmFornecedor = new DefaultTableModel();
        tmFornecedor.addColumn("ID");
        tmFornecedor.addColumn("Nome");
        tmFornecedor.addColumn("CNPJ");
        tmFornecedor.addColumn("Telefone");
        tmFornecedor.addColumn("Endereço");
        tmFornecedor.addColumn("Bairro");
        tmFornecedor.addColumn("CEP");
        tmFornecedor.addColumn("UF");
        
        jTable1.setModel(tmFornecedor);
        
        //Removo a coluna da View (JTable) mas mantenho na model para armazenar o ID
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
        
        //Para cada cliente resgatado do banco de dados, atualizo a tabela
        for(String[] f:linhasFornecedor)
        {
            tmFornecedor.addRow(f);
        }
        
        //Defino o tamanho para cada coluna
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jblBairro = new javax.swing.JLabel();
        jblCidade = new javax.swing.JLabel();
        jblUF = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jblEndereco = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jfCEP = new javax.swing.JFormattedTextField();
        jtCidade = new javax.swing.JTextField();
        jblNome = new javax.swing.JLabel();
        jfTelefone = new javax.swing.JFormattedTextField();
        jblTel = new javax.swing.JLabel();
        bntSalvar = new javax.swing.JButton();
        jtUF = new javax.swing.JTextField();
        jtEndereco = new javax.swing.JTextField();
        jblCEP = new javax.swing.JLabel();
        jblID = new javax.swing.JLabel();
        bntCancelar = new javax.swing.JButton();
        jblIDF = new javax.swing.JLabel();
        jblCNPJ = new javax.swing.JLabel();
        jfCNPJ = new javax.swing.JFormattedTextField();
        jblCampBairro = new javax.swing.JLabel();
        jblCampCidade = new javax.swing.JLabel();
        jblCampUF = new javax.swing.JLabel();
        jblCampCEP = new javax.swing.JLabel();
        jblCampEndereco = new javax.swing.JLabel();
        jblCampTel = new javax.swing.JLabel();
        jblCampCNPJ = new javax.swing.JLabel();
        jblCampNome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bntNovo = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        jtPesquisar = new javax.swing.JTextField();
        bntPesquisar = new javax.swing.JButton();
        bntRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jblBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblBairro.setText("*Bairro:");

        jblCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblCidade.setText("*Cidade:");

        jblUF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblUF.setText("*UF:");

        jblEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblEndereco.setText("*Endereço:");

        try {
            jfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jblNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblNome.setText("*Nome:");

        try {
            jfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jblTel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblTel.setText("*Telefone:");

        bntSalvar.setBackground(new java.awt.Color(153, 153, 153));
        bntSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntSalvar.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvar.setText("Salvar");
        bntSalvar.setBorderPainted(false);
        bntSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntSalvar.setFocusPainted(false);
        bntSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntSalvarMouseExited(evt);
            }
        });
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        jblCEP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblCEP.setText("*CEP:");

        jblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblID.setText("ID:");

        bntCancelar.setBackground(new java.awt.Color(153, 153, 153));
        bntCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bntCancelar.setText("Cancelar");
        bntCancelar.setBorderPainted(false);
        bntCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCancelar.setFocusPainted(false);
        bntCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntCancelarMouseExited(evt);
            }
        });
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        jblCNPJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jblCNPJ.setText("*CNPJ");

        try {
            jfCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jblCampBairro.setForeground(new java.awt.Color(255, 0, 0));
        jblCampBairro.setText("*Campo Obrigatório");

        jblCampCidade.setForeground(new java.awt.Color(255, 0, 0));
        jblCampCidade.setText("*Campo Obrigatório");

        jblCampUF.setForeground(new java.awt.Color(255, 0, 0));
        jblCampUF.setText("*Campo Obrigatório");

        jblCampCEP.setForeground(new java.awt.Color(255, 0, 0));
        jblCampCEP.setText("*Campo Obrigatório");

        jblCampEndereco.setForeground(new java.awt.Color(255, 0, 0));
        jblCampEndereco.setText("*Campo Obrigatório");

        jblCampTel.setForeground(new java.awt.Color(255, 0, 0));
        jblCampTel.setText("*Campo Obrigatório");

        jblCampCNPJ.setForeground(new java.awt.Color(255, 0, 0));
        jblCampCNPJ.setText("*Campo Obrigatório");

        jblCampNome.setForeground(new java.awt.Color(255, 0, 0));
        jblCampNome.setText("*Campo Obrigatório");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblID)
                            .addComponent(jblIDF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblNome)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblCampNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jblCNPJ)
                                        .addGap(71, 71, 71)
                                        .addComponent(jblTel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jblCidade))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jblCampCNPJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jblCampTel)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jblEndereco)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jblCampEndereco)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtEndereco)))))
                    .addComponent(jblBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblCampBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblCampCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jblCampUF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jblCampCEP))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jblUF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jblCEP))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jfCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblID)
                    .addComponent(jblNome)
                    .addComponent(jblCNPJ)
                    .addComponent(jblEndereco)
                    .addComponent(jblTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblIDF, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jblCampCNPJ)
                        .addComponent(jblCampNome))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jblCampTel)
                        .addComponent(jblCampEndereco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblBairro)
                    .addComponent(jblCidade)
                    .addComponent(jblUF)
                    .addComponent(jblCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtUF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblCampCidade)
                            .addComponent(jblCampBairro))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblCampUF)
                            .addComponent(jblCampCEP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bntNovo.setBackground(new java.awt.Color(153, 153, 153));
        bntNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntNovo.setForeground(new java.awt.Color(255, 255, 255));
        bntNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        bntNovo.setText("Novo");
        bntNovo.setBorderPainted(false);
        bntNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntNovo.setFocusPainted(false);
        bntNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntNovoMouseExited(evt);
            }
        });
        bntNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNovoActionPerformed(evt);
            }
        });

        bntEditar.setBackground(new java.awt.Color(153, 153, 153));
        bntEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntEditar.setForeground(new java.awt.Color(255, 255, 255));
        bntEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editt.png"))); // NOI18N
        bntEditar.setText("Editar");
        bntEditar.setBorderPainted(false);
        bntEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntEditar.setFocusPainted(false);
        bntEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntEditarMouseExited(evt);
            }
        });
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        bntPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        bntPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesquisar.png"))); // NOI18N
        bntPesquisar.setText("Pesquisar");
        bntPesquisar.setBorderPainted(false);
        bntPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntPesquisar.setFocusPainted(false);
        bntPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntPesquisarMouseExited(evt);
            }
        });

        bntRemover.setBackground(new java.awt.Color(153, 153, 153));
        bntRemover.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntRemover.setForeground(new java.awt.Color(255, 255, 255));
        bntRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        bntRemover.setText("Remover");
        bntRemover.setBorderPainted(false);
        bntRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntRemover.setFocusPainted(false);
        bntRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntRemoverMouseExited(evt);
            }
        });
        bntRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRemoverActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPesquisar)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntPesquisar))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPesquisar)
                    .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(bntNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntRemover))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSalvarMouseEntered
        // TODO add your handling code here:
        bntSalvar.setBackground(new Color(235,235,235));
        bntSalvar.setForeground(new Color(153,153,153));
        
    }//GEN-LAST:event_bntSalvarMouseEntered

    private void bntSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSalvarMouseExited
        // TODO add your handling code here:
        bntSalvar.setBackground(new Color(153,153,153));
        bntSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntSalvarMouseExited

    private void bntCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelarMouseEntered
        // TODO add your handling code here:
        bntCancelar.setBackground(new Color(235,235,235));
        bntCancelar.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntCancelarMouseEntered

    private void bntCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelarMouseExited
        // TODO add your handling code here:
        bntCancelar.setBackground(new Color(153,153,153));
        bntCancelar.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntCancelarMouseExited

    private void bntPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPesquisarMouseEntered
        // TODO add your handling code here:
        bntPesquisar.setBackground(new Color(235,235,235));
        bntPesquisar.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntPesquisarMouseEntered

    private void bntPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPesquisarMouseExited
        // TODO add your handling code here:
        bntPesquisar.setBackground(new Color(153,153,153));
        bntPesquisar.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntPesquisarMouseExited

    private void bntNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntNovoMouseEntered
        // TODO add your handling code here:
        bntNovo.setBackground(new Color(235,235,235));
        bntNovo.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntNovoMouseEntered

    private void bntNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntNovoMouseExited
        // TODO add your handling code here:
        bntNovo.setBackground(new Color(153,153,153));
        bntNovo.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntNovoMouseExited

    private void bntEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntEditarMouseEntered
        // TODO add your handling code here:
        bntEditar.setBackground(new Color(235,235,235));
        bntEditar.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntEditarMouseEntered

    private void bntEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntEditarMouseExited
        // TODO add your handling code here:
        bntEditar.setBackground(new Color(153,153,153));
        bntEditar.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntEditarMouseExited

    private void bntRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRemoverMouseEntered
        // TODO add your handling code here:
        bntRemover.setBackground(new Color(235,235,235));
        bntRemover.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntRemoverMouseEntered

    private void bntRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRemoverMouseExited
        // TODO add your handling code here:
        bntRemover.setBackground(new Color(153,153,153));
        bntRemover.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntRemoverMouseExited

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        // TODO add your handling code here:
       
       
        if (jtNome.getText().length() > 0) {
            jblCampNome.setVisible(false);
        } else {
            jblCampNome.setVisible(true);
        }
 
        if (jfCNPJ.getText().length() > 4) {
            jblCampCNPJ.setVisible(false);
        } else {
            jblCNPJ.setVisible(true);
        }
        if (jfTelefone.getText().length() > 0) {
            jblCampTel.setVisible(false);
        } else {
            jblCampTel.setVisible(true);
        }if (jtEndereco.getText().length() > 0) {
            jblCampEndereco.setVisible(false);
        } else {
            jblCampEndereco.setVisible(true);
        }if (jtBairro.getText().length() > 0) {
            jblCampBairro.setVisible(false);
        } else {
            jblCampBairro.setVisible(true);
        }if (jtCidade.getText().length() > 0) {
            jblCampCidade.setVisible(false);
        } else {
            jblCampCidade.setVisible(true);
        }if (jtUF.getText().length() > 0) {
            jblCampUF.setVisible(false);
        } else {
            jblCampUF.setVisible(true);
        }if (jfCEP.getText().length() > 0) {
            jblCampCEP.setVisible(false);
        } else {
            jblCampCEP.setVisible(true);
        }
       if ((jtNome.getText().length()>0)
                &&(jfCNPJ.getText().length()> 0)
                && (jfTelefone.getText().length() > 0) && (jfCEP.getText().length() > 0 
               && jtBairro.getText().length() > 0) && (jtCidade.getText().length() > 0) 
               && (jtEndereco.getText().length() > 0 && (jtUF.getText().length() > 0))) {
            JOptionPane.showMessageDialog(null, "Dados Validados aqui deve ser efetuada a operação!!");
        } else {
            JOptionPane.showMessageDialog(null, "Confira os campos Obrigatórios!!");
} 
      if(modoTela.equals("Criar"))
            {
                //Passo ao controller a entrada do usuário e peço para salvar no banco de dados
                if(FornecedorController.salvarFornecedor(jtNome.getText(),jfCNPJ.getText(), jtBairro.getText(),jfCEP.getText(), jtCidade.getText(), jtEndereco.getText(), jfTelefone.getText(), jtUF.getText()))
                {
                    //Recarrego a tabela com os dados resgatados do banco de dados
                    this.CarregarTabela();
                    
                    JOptionPane.showMessageDialog(null,"Fornecedor cadastrado com sucesso!");
                    LimparFormulario();
                }else{
                    JOptionPane.showMessageDialog(null,"Falha ao cadastrar Forncedor!");
                }

            }else
            {

                //Passo ao controller a entrada do usuário e peço para atualizar o banco de dados
                if(FornecedorController.atualizarFornecedor(Integer.parseInt(jblIDF.getText()), jtNome.getText(),jfCNPJ.getText(), jtBairro.getText(),jfCEP.getText(), jtCidade.getText(), jtEndereco.getText(), jfTelefone.getText(), jtUF.getText()))
                {
                    //Recarrego a tabela com os dados resgatados do banco de dados
                    this.CarregarTabela();
                    JOptionPane.showMessageDialog(this,"Fornecedor atualizado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(this,"Falha ao atualizar dados do Fornecedor!");
                }

            }

            LimparFormulario();
            DesabilitarFormulario();
        
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        this.DesabilitarFormulario();
        this.LimparFormulario();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void bntNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNovoActionPerformed
        // TODO add your handling code here:
        modoTela = "Criar";
        HabilitarFormulario();
    }//GEN-LAST:event_bntNovoActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        // TODO add your handling code here:
         modoTela = "Editar";
        
        //Verifico se há linhas para poder editar
        if(jTable1.getRowCount()>0)
        {
            //Verifico se o usuário selecionou alguma linha (Primeira linha = 0) | Nada selecionado = -1)
            if(jTable1.getSelectedRow()>=0)
            {
                HabilitarFormulario();
                
                //Variável acessória para identifcar se o formulário está em modo de edição ou alteração
                modoTela = "Editar";

                //Atribuo os valores que estão na linha selecionada para a tabela
                jblIDF.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString());
                jtNome.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1).toString());
                jfCNPJ.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2).toString());
                jtBairro.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3).toString());
                jfCEP.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4).toString());
                jtCidade.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5).toString());
                jtEndereco.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6).toString());
                jfTelefone.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 7).toString());
                jtUF.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 8).toString());
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Selecione um cliente para editar!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Não há cliente para editar!");
        }
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRemoverActionPerformed
        // TODO add your handling code here:
        if(jTable1.getRowCount()>0)
        {
            //Resgato o número da linha pelo JTable
            int numeroLinha = jTable1.getSelectedRow();
            
            //Resgato o ID (oculto) do cliente pelo JTableModel
            int IDfornecedor = Integer.parseInt(jTable1.getModel().getValueAt(numeroLinha, 0).toString());
            
            //Realizo a exclusão do cliente pelo ID
            if(FornecedorController.excluirFornecedor(IDfornecedor))
            {
                //Recarrego a tabela, consultando diretamente do banco de dados
                this.CarregarTabela();
                JOptionPane.showMessageDialog(this,"Forncedor excluído da base de dados");
            }else{
                JOptionPane.showMessageDialog(this,"Falha ao excluir o fornecedor!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Não há fornecedor para excluir!");
        }
        
        this.DesabilitarFormulario();
        this.LimparFormulario();
    }//GEN-LAST:event_bntRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           
        } catch (InstantiationException ex) {
           
        } catch (IllegalAccessException ex) {
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadForn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntNovo;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JButton bntRemover;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jblBairro;
    private javax.swing.JLabel jblCEP;
    private javax.swing.JLabel jblCNPJ;
    private javax.swing.JLabel jblCampBairro;
    private javax.swing.JLabel jblCampCEP;
    private javax.swing.JLabel jblCampCNPJ;
    private javax.swing.JLabel jblCampCidade;
    private javax.swing.JLabel jblCampEndereco;
    private javax.swing.JLabel jblCampNome;
    private javax.swing.JLabel jblCampTel;
    private javax.swing.JLabel jblCampUF;
    private javax.swing.JLabel jblCidade;
    private javax.swing.JLabel jblEndereco;
    private javax.swing.JLabel jblID;
    private javax.swing.JLabel jblIDF;
    private javax.swing.JLabel jblNome;
    private javax.swing.JLabel jblTel;
    private javax.swing.JLabel jblUF;
    private javax.swing.JFormattedTextField jfCEP;
    private javax.swing.JFormattedTextField jfCNPJ;
    private javax.swing.JFormattedTextField jfTelefone;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTextField jtUF;
    // End of variables declaration//GEN-END:variables
}
