/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador.view;

import java.awt.Color;

/**
 *
 * @author carlos.hmsousa1
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        Habilitar();
        initComponents();
        DesabilitarFormulario();
    }
    
    public void Habilitar(){
        this.jtQuant.setEnabled(true);
        this.jtIDP.setEnabled(true);
    }
    public void DesabilitarFormulario(){
        this.jtCV.setEnabled(false);
        this.jtDesc.setEnabled(false);
        this.jtValorTotal.setEnabled(false);
        this.jtValorUni.setEnabled(false);
        this.jtData.setEnabled(false);
        this.jtQuant.setEnabled(false);
        this.jtIDP.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bntCancelar = new javax.swing.JButton();
        bntFecharV = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtCV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bntAbrirV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bntAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtQuant = new javax.swing.JTextField();
        jtIDP = new javax.swing.JTextField();
        bntPes = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtDesc = new javax.swing.JTextField();
        jtValorUni = new javax.swing.JTextField();
        jtData = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bntRemover = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtValorTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        bntCancelar.setBackground(new java.awt.Color(153, 153, 153));
        bntCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bntCancelar.setText("Cancelar Venda");
        bntCancelar.setBorderPainted(false);
        bntCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCancelar.setFocusPainted(false);
        bntCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntCancelarMouseExited(evt);
            }
        });

        bntFecharV.setBackground(new java.awt.Color(153, 153, 153));
        bntFecharV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntFecharV.setForeground(new java.awt.Color(255, 255, 255));
        bntFecharV.setText("Fechar Venda");
        bntFecharV.setBorderPainted(false);
        bntFecharV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntFecharV.setFocusPainted(false);
        bntFecharV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntFecharVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntFecharVMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ALT + F8");

        jtCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCVActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ALT + F9");

        bntAbrirV.setBackground(new java.awt.Color(153, 153, 153));
        bntAbrirV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntAbrirV.setForeground(new java.awt.Color(255, 255, 255));
        bntAbrirV.setText("Abrir Venda");
        bntAbrirV.setBorderPainted(false);
        bntAbrirV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntAbrirV.setFocusPainted(false);
        bntAbrirV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntAbrirVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntAbrirVMouseExited(evt);
            }
        });
        bntAbrirV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAbrirVActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Código Venda:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("ALT + F10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel4)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bntAbrirV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntFecharV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtCV, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAbrirV)
                    .addComponent(bntFecharV)
                    .addComponent(bntCancelar)
                    .addComponent(jtCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Valor Unitário:");

        bntAdd.setBackground(new java.awt.Color(153, 153, 153));
        bntAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntAdd.setForeground(new java.awt.Color(255, 255, 255));
        bntAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/venda.png"))); // NOI18N
        bntAdd.setText("Add Item");
        bntAdd.setBorderPainted(false);
        bntAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntAdd.setFocusPainted(false);
        bntAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntAddMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ID Produto:");

        bntPes.setBackground(new java.awt.Color(153, 153, 153));
        bntPes.setForeground(new java.awt.Color(255, 255, 255));
        bntPes.setText("...");
        bntPes.setBorderPainted(false);
        bntPes.setFocusPainted(false);
        bntPes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntPesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntPesMouseExited(evt);
            }
        });
        bntPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Data:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Descrição Produto:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Quantidade:");

        jtValorUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtValorUniActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("ALT + F11");

        bntRemover.setBackground(new java.awt.Color(153, 153, 153));
        bntRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntRemover.setForeground(new java.awt.Color(255, 255, 255));
        bntRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        bntRemover.setText("Remover");
        bntRemover.setBorderPainted(false);
        bntRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntRemover.setFocusPainted(false);
        bntRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntRemoverMouseExited(evt);
            }
        });
        bntRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtValorUni)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtIDP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(bntPes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bntAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntPes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntAdd)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Valor Total:");

        jtValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtValorTotalActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Quant.", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtValorTotal))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCVActionPerformed

    private void jtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtValorTotalActionPerformed

    private void bntPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesActionPerformed
        // TODO add your handling code here:
        TelaProduto tep = new TelaProduto();
        tep.setVisible(true);
    }//GEN-LAST:event_bntPesActionPerformed

    private void bntRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRemoverActionPerformed

    private void jtValorUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtValorUniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtValorUniActionPerformed

    private void bntAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAddMouseEntered
        // TODO add your handling code here:
        bntAdd.setBackground(new Color(235,235,235));
        bntAdd.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntAddMouseEntered

    private void bntRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRemoverMouseEntered
        // TODO add your handling code here:
        bntRemover.setBackground(new Color(235,235,235));
        bntRemover.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntRemoverMouseEntered

    private void bntAbrirVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAbrirVMouseEntered
        // TODO add your handling code here:
        bntAbrirV.setBackground(new Color(235,235,235));
        bntAbrirV.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntAbrirVMouseEntered

    private void bntFecharVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntFecharVMouseEntered
        // TODO add your handling code here:
        bntFecharV.setBackground(new Color(235,235,235));
        bntFecharV.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntFecharVMouseEntered

    private void bntCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelarMouseEntered
        // TODO add your handling code here:
        bntCancelar.setBackground(new Color(235,235,235));
        bntCancelar.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntCancelarMouseEntered

    private void bntPesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPesMouseEntered
        // TODO add your handling code here:
        bntPes.setBackground(new Color(235,235,235));
        bntPes.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_bntPesMouseEntered

    private void bntPesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPesMouseExited
        // TODO add your handling code here:
        bntPes.setBackground(new Color(153,153,153));
        bntPes.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntPesMouseExited

    private void bntAbrirVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAbrirVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAbrirVActionPerformed

    private void bntAbrirVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAbrirVMouseExited
        // TODO add your handling code here:
        bntAbrirV.setBackground(new Color(153,153,153));
        bntAbrirV.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntAbrirVMouseExited

    private void bntFecharVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntFecharVMouseExited
        // TODO add your handling code here:
        bntFecharV.setBackground(new Color(153,153,153));
        bntFecharV.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntFecharVMouseExited

    private void bntCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelarMouseExited
        // TODO add your handling code here:
        bntCancelar.setBackground(new Color(153,153,153));
        bntCancelar.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntCancelarMouseExited

    private void bntAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAddMouseExited
        // TODO add your handling code here:
        bntAdd.setBackground(new Color(153,153,153));
        bntAdd.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntAddMouseExited

    private void bntRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRemoverMouseExited
        // TODO add your handling code here:
        bntRemover.setBackground(new Color(153,153,153));
        bntRemover.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntRemoverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAbrirV;
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntFecharV;
    private javax.swing.JButton bntPes;
    private javax.swing.JButton bntRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtCV;
    private javax.swing.JTextField jtData;
    private javax.swing.JTextField jtDesc;
    private javax.swing.JTextField jtIDP;
    private javax.swing.JTextField jtQuant;
    private javax.swing.JTextField jtValorTotal;
    private javax.swing.JTextField jtValorUni;
    // End of variables declaration//GEN-END:variables
}
